import vakilBotstyles from "../styles/vakilbot.module.css";
import Head from "next/head";
import svg from "../images/tick.svg";
import Image from "next/image";
import App from "../components/App.js";

export default function legalBot(){

    return <div>
        <Head>
        <title>VakilBot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"></link>
        </Head>
       
        
        
        <div className={`container-md ${vakilBotstyles.container}`}>
        <div className={vakilBotstyles.wholepage}>
        <App />
        <div className={vakilBotstyles.Intro}>
            <span className={vakilBotstyles.Introhead} >Know Your Rights. <br></br></span>
            <span className={vakilBotstyles.Intropara}>VakilBot impovers you to fight unjust <br></br>traffic challans and dirty cops<br></br>soliciting bribes.</span>
        </div>
        
        <div className={vakilBotstyles.text}>Take the first step in fighting corruption.</div>
        <div className={vakilBotstyles.form}>
          <form action="/thankyou" method="post">
          <div className={vakilBotstyles.f}>
          <div className={vakilBotstyles.input1}><input className={vakilBotstyles.ph} placeholder="Email or Phone Number"></input></div>
          <div className={vakilBotstyles.input2}><input className={vakilBotstyles.go} type="submit" value="Go"></input></div>
          </div>
          </form>
          </div>
          <div className={vakilBotstyles.agreement}>By signing up, you are agreeing to VakilBot term’s & conditions & for us to contact you through the phone number & email provided.</div>
        <div className={vakilBotstyles.foot}>AT THE TIP OF YOUR FINGER, GET ACCESS TO:</div>

        <div className={vakilBotstyles.ppt}>
        <div className={vakilBotstyles.m}>
        <div className={vakilBotstyles.pts}>
            <div className={vakilBotstyles.pi1}><Image src= {svg} /></div>
            <div className={vakilBotstyles.t1}>Information regarding penalties</div>
        </div>

        <div className={vakilBotstyles.pts}>
            <div className={vakilBotstyles.pi1}><Image src= {svg} /></div>
            <div className={vakilBotstyles.t1}>Legal help against unjust tickets</div>
        </div>

        <div className={vakilBotstyles.pts}>
            <div className={vakilBotstyles.pi1}><Image src= {svg} /></div>
            <div className={vakilBotstyles.t1}>Legal protection from corrupt cops</div>
        </div>
        </div>
        </div>
        </div>
    </div>
    </div>
}